name: CI/CD pipline

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  test:
    name: Prepare E2E tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare for tests
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip install -r requirements.txt
          docker build . --file Dockerfile --tag payment-service:latest
          docker run -p 5000:5000 -d payment-service:latest
          sleep 5

      - name: Run tests
        run: |
          python3 test_company_service.py

  build-and-push-to-dh:
    name: Build and push to DockerHub
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3

      - name: Build docker image
        run: |
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/delivery-service:latest

      - name: Test solution
        run: |
          echo There will be tests later

      - name: Login to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push tag to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/delivery-service:latest
